### ISSUE TITLE
Entry in Superfecta-Scheme returns an error if the certificate has expired

### ISSUE THREAD

**Issue by shamrockDE** [Massi-X/freepbx-carddavmiddleware-ui#13]
First: Thanks a million for this new version. I've installed it in my FreePBX and i got it working!
I found two problems, i will open an issue for both.

**Describe the bug**
Entry in Superfecta-Scheme returns error "Peer's Certificate has expired." if the certificate is expired

**To Reproduce**
1. Go to Superfecta Scheme
2. Start "Debug/Test Run Scheme"
3. Enter any number
4. See error:

> Start Schema carddavmiddleware
> Executing Regular Expressions 2
> Parsed POST data is: number=01622403018
> Retrieving URL https://localhost:443/carddavmiddleware/numbertocnam.php
> Peer's Certificate has expired.
> Something went wrong, url returned empty.
> result took 0.1193 seconds.

**Workaround**
In Superfecta Scheme change the URL manually from `https://localhost:443/carddavmiddleware/numbertocnam.php` to `http://localhost/carddavmiddleware/numbertocnam.php`
Without SSL the scheme returns the correct result, means it returns the name for the number

**Possible Solution**
There are three possible solutions (may be there are even more):
1. What i can do: install a new certificate, which isn't expired
2. In carddavmiddleware add a button to change the URL between `Using SSL` and `Not Using SSL`, so change `https://` to `http://`
3. In carddavmiddleware add a button to ignore certificate errors.

**Comment by Massi-X** [comment]
Hi thank you for the feedback! There is always something you don't consider even after months of testing 🤯

OK so here the issue I see is that obviously localhost cannot have a valid certificate (because it's missing the domain name). It may be possible to add an exception in the system but this is not the correct way to handle it.

So about your solutions:
1. Should not be viable
2. Is the correct way but I think it should always fallback to http only, but need some testing
3. The check is done by superfecta, so for sure this is not possible

I will look into it

**Comment by Massi-X** [comment]
Closed with f3da374
